### PR TITLE
CMR-76 Rename LocalVariants as LocalVarLabels

### PR DESCRIPTION
**Pull request by ebtoner**
In order to be consistent with cm_local_var_label naming convention, I've updated anything with the LocalVariant / LocalVariants and local_variant / local_variants to LocalVarLabel / LocalVarLabels and local_var_label / local_var_labels.

### CODE REVIEW

**Review by dkinzer — CHANGES_REQUESTED** [review]
Can we please remove the swagger/yaml changes swagger/v1/swagger.yaml ... It's a mistake that we have this file version controlled and I have PR to build this in the docker container instead:  https://github.com/tulibraries/centralized-metadata/pull/89

The database is already established so we need to make schema changes to it via migrations.  I think what I'm seeing is that you updated an old migration to "create" the new schema.  But I think that wont work in k8 environment because there already is a database  and it needs update statements to change the name of the table fields etc.

**Comment by dkinzer** [comment]
@ebtoner another possibility with regards to database changes is for us to delete our k8 database and rebuild it from scratch ... If we do that you wont have to use migrations and what you this in this PR will work just fine.

**Comment by ebtoner** [comment]
@dkinzer -- I basically just did find and replace. Please just let me know how you'd like to handle this.

**Comment by dkinzer** [comment]
Yeah, I'm not hung up on it or anything it's just considered best practice (https://github.com/tulibraries/centralized-metadata/blob/main/db/schema.rb#L1-L11)  I'm pretty sure the deployment will fail as is.  But writing a migration for all these changes is no easy task either.

I tried giving it a shot but it's messy and I'm pretty sure I missed something:

```
class RenameLocalVariantSchema < ActiveRecord::Migration[7.0]
  def change

    remove_index :local_variants, :local_metadatum_id

    remove_index :local_variants, name: 'index_local_variants_on_local_m
etadatum_id'
    remove_foreign_key :local_variants, column: :local_metadata

    rename_table :local_variants, :local_var_labels

    add_index :local_var_labels, :local_metadatum_id, name: 'index_local_var_labels_on_local
_metadatum_id', unique: true


    add_foreign_key :local_var_labels, column: :new_parent_column_name

  end
end
```

I think the easiest thing is to delete our current database and then rebuild the database using this new schema.

**Pull request merged**
